source 'https://rubygems.org'

gem 'jekyll', '~> 4.0'
gem 'kramdown', '= 2.1.0'
gem 'jemoji', '~> 0.11.1'
gem 'jekyll-paginate', '~> 1.1.0'
gem 'concurrent-ruby', '~> 1.1.7'
gem 'logger'
gem 'csv'
gem 'ostruct'
gem 'rexml'
gem 'webrick'
