source 'https://rubygems.org'

gem 'jekyll', '~> 4.3.4'
gem 'jekyll-sass-converter', '~> 3.0'
gem 'kramdown', '~> 2.4'
gem 'kramdown-parser-gfm'
gem 'jemoji', '~> 0.11.1'
gem 'jekyll-paginate', '~> 1.1.0'
gem 'concurrent-ruby', '~> 1.1.7'
gem 'logger'
gem 'csv'
gem 'ostruct'
gem 'rexml'
gem 'webrick'
